import type { CaptureRecipe } from "./types";

export const automationAiRecipes: CaptureRecipe[] = [
  {
    docSlug: "workflows",
    title: "Workflows",
    route: "/workflows",
    video: true,
    steps: [
      { kind: "goto", path: "/workflows", caption: "A workflow is a trigger plus a sequence of actions.", waitFor: { role: "heading", name: "Workflows" } },
      { kind: "shot", name: "list", alt: "The workflows list showing each automation's trigger", sectionId: "triggers" },
      { kind: "caption", text: "Seven triggers, from a deal changing stage to a form being submitted." },
      { kind: "shot", name: "triggers", alt: "Workflow trigger types", sectionId: "triggers" },
      { kind: "caption", text: "Active and inactive workflows are separated, so you can test before switching on." },
      { kind: "shot", name: "active", alt: "Active and inactive workflows", sectionId: "managing" },
    ],
  },
  {
    docSlug: "workflow-builder",
    title: "Workflow builder",
    route: "/workflows/builder",
    video: true,
    steps: [
      { kind: "goto", path: "/workflows/builder", caption: "The builder is a canvas: place a trigger, then chain actions.", settleMs: 3500 },
      { kind: "shot", name: "canvas", alt: "The workflow builder canvas", sectionId: "building" },
      { kind: "caption", text: "Selecting a node opens its configuration panel." },
      { kind: "shot", name: "panel", alt: "Node configuration panel in the workflow builder", sectionId: "message-steps" },
      { kind: "caption", text: "Conditions let one workflow behave differently for different patients." },
      { kind: "shot", name: "conditions", alt: "Condition configuration", sectionId: "building" },
    ],
  },
  {
    docSlug: "email-templates",
    title: "Email templates",
    route: "/workflows/templates",
    video: true,
    steps: [
      { kind: "goto", path: "/workflows/templates", caption: "One library, shared by manual email, workflows and campaigns.", waitFor: { role: "heading", name: "Email Templates" } },
      { kind: "shot", name: "library", alt: "The email template library", sectionId: "creating" },
      { kind: "caption", text: "Name templates so colleagues can pick the right one from a list." },
      { kind: "shot", name: "template", alt: "An email template", sectionId: "creating" },
    ],
  },
  {
    docSlug: "marketing-campaigns",
    title: "Marketing campaigns",
    route: "/marketing",
    video: true,
    steps: [
      { kind: "goto", path: "/marketing", caption: "Saved audience lists and the history of every campaign sent.", waitFor: { role: "heading", name: "Marketing" } },
      { kind: "shot", name: "overview", alt: "Marketing overview with saved lists and campaign history", sectionId: "history" },
      { kind: "goto", path: "/marketing/campaigns", caption: "Build an audience by filter, preview it, pick a template, send.", waitFor: { role: "heading", name: "Marketing Campaigns" } },
      { kind: "shot", name: "audience", alt: "Campaign audience filters", sectionId: "building-an-audience" },
      { kind: "caption", text: "Preview the recipients before sending — the last chance to catch a filter mistake." },
      { kind: "shot", name: "preview", alt: "Campaign recipient preview and template selection", sectionId: "sending" },
    ],
  },
  {
    docSlug: "ai-agents",
    title: "AI voice agents",
    route: "/agents",
    video: true,
    steps: [
      { kind: "goto", path: "/agents", caption: "Agents take the calls the clinic cannot answer.", waitFor: { role: "heading", name: "AI Agents" } },
      { kind: "shot", name: "dropped-calls", alt: "Dropped calls with status and assignment", sectionId: "dropped-calls" },
      { kind: "caption", text: "The important half is what happens afterwards: every dropped call gets a status and an owner." },
      { kind: "shot", name: "statuses", alt: "Dropped call statuses", sectionId: "dropped-calls" },
      { kind: "caption", text: "Round-robin spreads callbacks so one person does not absorb them all." },
      { kind: "shot", name: "assignment", alt: "Round-robin assignment", sectionId: "assignment" },
    ],
  },
  {
    docSlug: "aliice-assistant",
    title: "Aliice assistant & chat widget",
    route: "/chat",
    video: true,
    steps: [
      { kind: "goto", path: "/chat", caption: "Staff ask the assistant questions and draft text with it.", settleMs: 3000 },
      { kind: "shot", name: "chat", alt: "The Aliice assistant chat", sectionId: "staff-chat" },
      { kind: "goto", path: "/prompt", caption: "The knowledge base is how the assistant learns your clinic.", settleMs: 2500 },
      { kind: "shot", name: "knowledge", alt: "The AI knowledge base organised as topics", sectionId: "knowledge-base" },
      { kind: "goto", path: "/aliicechatembed", caption: "The same assistant can be embedded on your website.", settleMs: 2000 },
      { kind: "shot", name: "widget", alt: "The chat widget install page with copy-paste snippets", sectionId: "chat-widget" },
    ],
  },
  {
    docSlug: "controllers",
    title: "Staff availability controllers",
    route: "/controllers",
    video: true,
    steps: [
      { kind: "goto", path: "/controllers", caption: "Each user's normal working pattern shapes the calendar views.", waitFor: { role: "heading", name: "Controllers" } },
      { kind: "shot", name: "list", alt: "Controllers with per-user availability", sectionId: "setting-availability" },
      { kind: "caption", text: "Available days with start and end times, summarised so mistakes stand out." },
      { kind: "shot", name: "schedule", alt: "Per-weekday availability with start and end times", sectionId: "setting-availability" },
    ],
  },
  {
    docSlug: "seo-content-hub",
    title: "SEO & AEO content hub",
    route: "/aeo",
    video: false,
    steps: [
      { kind: "goto", path: "/aeo", caption: "Keyword data, a content plan, and generated articles.", settleMs: 3000 },
      { kind: "shot", name: "hub", alt: "The AEO and SEO content hub", sectionId: "keywords" },
      { kind: "shot", name: "plan", alt: "The content plan with priority and status", sectionId: "content-plan" },
    ],
  },
];
