import type { CaptureRecipe } from "./types";

export const schedulingRecipes: CaptureRecipe[] = [
  {
    docSlug: "agenda",
    title: "Agenda",
    route: "/appointments",
    video: true,
    steps: [
      { kind: "goto", path: "/appointments", caption: "The agenda is the busiest screen in the platform.", settleMs: 4000 },
      { kind: "shot", name: "day-view", alt: "The agenda day view with a column per doctor", sectionId: "views" },
      { kind: "caption", text: "Day, range and month views answer different questions." },
      { kind: "shot", name: "toolbar", alt: "The agenda toolbar with the view selector and date navigation", sectionId: "views" },
      { kind: "caption", text: "Drag across the time you need and the appointment takes that duration." },
      { kind: "shot", name: "grid", alt: "The agenda time grid used to drag-create appointments", sectionId: "booking-an-appointment" },
      { kind: "caption", text: "Colour comes from the appointment category, which is what makes a full day readable." },
      { kind: "shot", name: "categories", alt: "Colour-coded appointments by category", sectionId: "categories-and-colours" },
      { kind: "goto", path: "/appointments/cancelled", caption: "Cancellations get their own page so they are worked, not forgotten.", waitFor: { role: "heading", name: "Cancelled appointments" } },
      { kind: "shot", name: "cancelled", alt: "The cancelled appointments page", sectionId: "cancelled-appointments" },
    ],
  },
  {
    docSlug: "doctor-availability",
    title: "Doctor availability",
    route: "/settings",
    video: true,
    steps: [
      { kind: "goto", path: "/settings", caption: "Availability is configured once, in Settings.", waitFor: { role: "heading", name: "Settings" } },
      { kind: "shot", name: "settings", alt: "The Settings screen with its eight tabs", sectionId: "working-hours" },
      { kind: "click", target: { text: "Doctor Scheduling" }, caption: "Doctor Scheduling holds working hours and slot durations.", optional: true },
      { kind: "wait", ms: 1500 },
      { kind: "shot", name: "scheduling", alt: "Doctor scheduling settings", sectionId: "working-hours" },
      { kind: "click", target: { text: "Doctor Days Off" }, caption: "Individual absences go here.", optional: true },
      { kind: "wait", ms: 1500 },
      { kind: "shot", name: "days-off", alt: "Doctor days off settings", sectionId: "days-off" },
      { kind: "click", target: { text: "Blocked Dates" }, caption: "Blocked dates close the clinic for everyone.", optional: true },
      { kind: "wait", ms: 1500 },
      { kind: "shot", name: "blocked-dates", alt: "Clinic-wide blocked dates", sectionId: "blocked-dates" },
    ],
  },
  {
    docSlug: "online-bookings",
    title: "Online booking",
    route: "/bookings",
    video: true,
    steps: [
      { kind: "goto", path: "/bookings", caption: "Everything patients book themselves arrives here.", waitFor: { role: "heading", name: "Online Bookings" } },
      { kind: "shot", name: "inbox", alt: "Online bookings with status counts and filters", sectionId: "managing-bookings" },
      { kind: "caption", text: "Totals per status let you work a queue rather than a list." },
      { kind: "shot", name: "statuses", alt: "Booking status totals", sectionId: "managing-bookings" },
      { kind: "goto", path: "/book-appointment", caption: "This is what the patient sees.", settleMs: 2500 },
      { kind: "shot", name: "public-page", alt: "The public booking page", sectionId: "the-public-page" },
      { kind: "goto", path: "/book-appointment/doctors", caption: "Each bookable doctor also has their own page.", settleMs: 2500 },
      { kind: "shot", name: "doctor-pages", alt: "Per-doctor booking pages", sectionId: "doctor-pages" },
    ],
  },
  {
    docSlug: "appointment-reminders",
    title: "Appointment reminders",
    route: "/settings",
    video: false,
    steps: [
      { kind: "goto", path: "/settings", caption: "Reminder wording lives in the WhatsApp templates.", waitFor: { role: "heading", name: "Settings" } },
      { kind: "click", target: { text: "WhatsApp Templates" }, caption: "Templates used by automated appointment messages.", optional: true },
      { kind: "wait", ms: 1500 },
      { kind: "shot", name: "templates", alt: "WhatsApp message templates used for reminders", sectionId: "channels" },
      { kind: "goto", path: "/appointments", caption: "The agenda status is what suppresses a reminder.", settleMs: 3500 },
      { kind: "shot", name: "agenda-statuses", alt: "Appointments whose status controls whether reminders are sent", sectionId: "when-nothing-is-sent" },
    ],
  },
];
