import type { DocModule } from "./types";

export const communicationModules: DocModule[] = [
  {
    slug: "email",
    title: "Email",
    tagline: "Send, receive, schedule and track patient email without leaving the platform.",
    category: "communication",
    icon: "mail",
    appPath: ["Patient file", "Email"],
    audience: ["staff", "admin", "doctor"],
    summary:
      "Email is sent from inside the patient record, so correspondence stays attached to the person it concerns. Replies come back into the platform, scheduled email goes out on its own, and every message can be tracked in Email Reports with its delivery status.",
    keyCapabilities: [
      "Send email to a patient from their record",
      "Use templates instead of retyping standard messages",
      "Attach documents and photos already on the file",
      "Schedule email to go out later",
      "Receive replies in the platform",
      "Track sent, failed, queued and draft messages",
      "Sign email automatically with your own signature",
    ],
    sections: [
      {
        id: "sending",
        heading: "Sending an email",
        steps: [
          { title: "Open the patient", body: "Email is composed from the record so it is filed automatically." },
          {
            title: "Start a message",
            body: "The patient's address is filled in from the record. Check it on records created from imported lists.",
          },
          {
            title: "Use a template if one fits",
            body: "Templates cover the messages you send repeatedly — appointment information, aftercare, quotes, document delivery.",
          },
          {
            title: "Attach anything needed",
            body: "Documents, photographs and generated paperwork already on the patient file can be attached directly.",
          },
          {
            title: "Send, or schedule",
            body: "Scheduled messages are queued and sent automatically at the right time.",
          },
        ],
        callouts: [
          {
            kind: "note",
            body: "Your profile signature is appended automatically, so patients see a consistent sign-off whoever writes.",
          },
        ],
      },
      {
        id: "templates",
        heading: "Templates",
        intro:
          "Templates live in the workflow templates library and are shared by manual sending, workflows and campaigns — so a change to a template changes it everywhere.",
        bullets: [
          "Design templates once and reuse them across automation and manual sending",
          "Templates can be built from existing HTML if your clinic already has branded email",
          "Because workflows use the same templates, automated aftercare looks like your manual correspondence",
        ],
      },
      {
        id: "receiving",
        heading: "Receiving replies",
        bullets: [
          "Patient replies arrive in the platform rather than in one person's mailbox",
          "The Email Replies page lists incoming replies needing attention",
          "An unread counter in the header tells you when replies are waiting",
          "Replies are attached to the patient, so the whole thread is visible in the file",
        ],
        callouts: [
          {
            kind: "tip",
            body: "Reminder emails are sent with the clinic's own reply-to address, so a patient answering an automated reminder still reaches a person.",
          },
        ],
      },
      {
        id: "email-reports",
        heading: "Email reports",
        intro:
          "Email Reports is the delivery log. It shows totals and lets you filter down to a single problem message.",
        table: {
          columns: ["Filter", "Options"],
          rows: [
            ["Direction", "Inbox or outbox"],
            ["Status", "Draft, queued, sent, failed"],
            ["Source", "Manual, or generated by automation"],
            ["Date range", "Any two dates"],
            ["Search", "Free text across the log"],
          ],
        },
        bullets: [
          "Headline counts for total emails, sent successfully and failed",
          "Failures are visible rather than silent, which is how you catch a wrong address or a bounced domain",
          "Doctors can see the correspondence sent under their own address",
        ],
      },
      {
        id: "scheduled-email",
        heading: "Scheduled and automated email",
        bullets: [
          "Scheduled messages are processed automatically every hour",
          "Appointment confirmations and reminders are sent by their own schedule",
          "Marketing campaigns and workflows send through the same email system, so everything appears in the same reports",
        ],
        callouts: [
          {
            kind: "important",
            body: "Patient email is medical correspondence. Check the recipient, avoid clinical detail in subject lines, and use the patient's language preference — it is recorded on the record for exactly this reason.",
          },
        ],
      },
    ],
    faqs: [
      {
        question: "A patient says our email went to spam.",
        answer:
          "Check Email Reports for the send status first. If it was sent successfully, the issue is on the receiving side — sending from a properly configured clinic domain, which your administrator sets up, is what fixes it long term.",
      },
      {
        question: "Can I send from my own mailbox instead?",
        answer:
          "You can, but then the correspondence is not on the patient file and nobody else can see it. Sending from the platform is what keeps the record complete.",
      },
    ],
    related: ["whatsapp", "communication-logs", "marketing-campaigns", "workflows", "email-templates"],
    keywords: ["email", "templates", "replies", "inbox", "delivery", "bounce", "scheduled email", "signature"],
  },

  {
    slug: "whatsapp",
    title: "WhatsApp",
    tagline: "The channel patients actually read — conversations, templates and queued sending.",
    category: "communication",
    icon: "chat",
    appPath: ["Header", "WhatsApp"],
    audience: ["staff", "admin"],
    summary:
      "WhatsApp is the primary channel for appointment confirmations, reminders and quick follow-up, because read rates are far higher than email. Conversations are visible in the platform, messages are queued so delivery can be retried, and templates keep repeated messages consistent.",
    keyCapabilities: [
      "See WhatsApp conversations with patients",
      "Get an unread counter in the header",
      "Send messages from the platform",
      "Use maintained message templates",
      "Have confirmations and reminders sent automatically",
      "Re-send messages that failed",
      "Have delivery status reported back",
    ],
    sections: [
      {
        id: "conversations",
        heading: "Working conversations",
        steps: [
          { title: "Open WhatsApp from the header", body: "The icon carries an unread count." },
          { title: "Pick a conversation", body: "Conversations are matched to the patient where the number is recognised." },
          { title: "Reply", body: "The message is queued and sent, and recorded against the patient." },
        ],
        callouts: [
          {
            kind: "tip",
            body: "If an inbound number is not matched to anyone, it is usually a new enquiry. Create the patient from it so the conversation is not lost.",
          },
        ],
      },
      {
        id: "templates",
        heading: "Message templates",
        intro:
          "Templates are maintained under Settings › WhatsApp Templates and are used by both manual sending and automation.",
        bullets: [
          "Keep confirmations, reminders and follow-ups consistent across the team",
          "Automated appointment messages use these templates",
          "Templates can carry the patient's details so the message reads personally",
        ],
      },
      {
        id: "automatic-messages",
        heading: "Automatic WhatsApp messages",
        table: {
          columns: ["Message", "When"],
          rows: [
            ["Booking confirmation", "Around an hour after an appointment is created."],
            ["Appointment reminder", "The day before the appointment."],
            ["Workflow messages", "Whenever a workflow with a WhatsApp step runs."],
            ["Scheduled messages", "Queued messages are processed on a schedule."],
          ],
        },
        bullets: [
          "WhatsApp is attempted first for appointment messages, with email sent in parallel",
          "Nothing is sent for appointments tagged as moved or cancelled",
          "Internal calendars such as the operation room never message patients",
        ],
      },
      {
        id: "queue-and-failures",
        heading: "Queueing, delivery and failures",
        bullets: [
          "Messages go through a queue rather than being fired directly, so a temporary outage does not lose them",
          "Delivery status is reported back and recorded",
          "Where a message failed because of a bad number, correct the number and use the resend page to try again",
        ],
        callouts: [
          {
            kind: "warning",
            body: "WhatsApp depends on the clinic's connection being live. If it drops, appointment messages still go out by email — but manual conversations will wait. Ask an administrator to check the connection if sending stops working.",
          },
        ],
      },
      {
        id: "good-practice",
        heading: "Good practice",
        bullets: [
          "Store mobile numbers in international format; imported numbers are normalised for Switzerland automatically",
          "Keep clinical detail out of WhatsApp — use it for logistics and use email or the patient app for anything sensitive",
          "Write in the patient's preferred language, which is recorded on their record",
        ],
      },
    ],
    related: ["appointment-reminders", "email", "communication-logs", "settings"],
    keywords: ["whatsapp", "messages", "templates", "reminders", "queue", "conversations", "mobile"],
  },

  {
    slug: "sms",
    title: "SMS",
    tagline: "Text messaging as a fallback where WhatsApp will not reach.",
    category: "communication",
    icon: "phone",
    appPath: ["Patient file", "Messages"],
    audience: ["staff", "admin"],
    summary:
      "SMS is available for patients who do not use WhatsApp, or where a message must arrive regardless of an internet connection. Sends are logged so they appear in the patient's communication history alongside every other channel.",
    keyCapabilities: [
      "Send a text message to a patient",
      "Keep sends in the patient's communication history",
      "Review a log of SMS activity",
      "Use SMS as a fallback in automation",
    ],
    sections: [
      {
        id: "when-to-use",
        heading: "When to use SMS",
        bullets: [
          "The patient does not use WhatsApp",
          "The message is short, urgent and purely logistical — a same-day change, for instance",
          "An older patient group where text is the familiar channel",
        ],
        callouts: [
          {
            kind: "note",
            body: "SMS costs money per message and offers no delivery receipt as rich as WhatsApp's. Prefer WhatsApp where the patient uses it.",
          },
        ],
      },
      {
        id: "sending",
        heading: "Sending and logging",
        steps: [
          { title: "Open the patient", body: "So the message is attached to their record." },
          { title: "Send the message", body: "Keep it short — the patient will read it on a lock screen." },
          {
            title: "Check the log",
            body: "SMS activity is logged, so the send appears in the patient's history and in the communication logs.",
          },
        ],
      },
      {
        id: "limits",
        heading: "Limits to keep in mind",
        bullets: [
          "No attachments — send a link, or use email for documents",
          "No threaded conversation as rich as WhatsApp",
          "Never put clinical detail in a text message",
          "Numbers must be correct and in international format to be deliverable",
        ],
      },
    ],
    related: ["whatsapp", "email", "communication-logs"],
    keywords: ["sms", "text message", "twilio", "fallback", "mobile", "notifications"],
  },

  {
    slug: "internal-chat-and-comments",
    title: "Comments, mentions & tasks",
    tagline: "How the team talks to each other about a patient without emailing.",
    category: "communication",
    icon: "clipboard",
    appPath: ["Menu", "Tasks"],
    audience: ["staff", "admin", "doctor"],
    summary:
      "Internal communication happens on the record it concerns: notes on the patient file and comments on tasks, both with @mentions that notify the person named. Everything addressed to you collects in one place with an unread counter, so nothing depends on someone remembering to tell you.",
    keyCapabilities: [
      "Comment on tasks and write notes on patients",
      "@mention a colleague to notify them",
      "See every mention addressed to you in one list",
      "Filter mentions by read and unread",
      "Mark mentions as read in bulk",
      "Create, assign and track tasks",
    ],
    sections: [
      {
        id: "mentions",
        heading: "Mentions",
        intro:
          "A mention is the internal equivalent of tapping a colleague on the shoulder, except it is attached to the patient or task in question and does not get lost.",
        steps: [
          { title: "Write a note or a task comment", body: "On the patient file, or on the task." },
          { title: "Type @ and pick the colleague", body: "They are notified." },
          {
            title: "They see it in Comments",
            body: "The header counter increases, and the mention appears in their list with the context it came from.",
          },
        ],
        bullets: [
          "Mentions from patient notes and from task comments are collected together",
          "Filter by all, unread or read",
          "Mark everything read at once when you have worked through them",
        ],
      },
      {
        id: "tasks",
        heading: "Tasks",
        intro:
          "Tasks are the unit of follow-up. They have an owner, so responsibility is explicit, and they can be created automatically.",
        bullets: [
          "Assign a task to a colleague with what needs doing",
          "Discuss it in comments on the task itself, not over email",
          "The header task counter shows what is open and assigned to you",
          "Workflows can create tasks automatically — after a cancellation or a missed call, for example",
        ],
        callouts: [
          {
            kind: "tip",
            body: "Anything that needs doing to a patient later belongs in a task, not in a note. Notes record; tasks get done.",
          },
        ],
      },
      {
        id: "notifications-centre",
        heading: "The notification centre",
        intro:
          "The header icons are each a separate queue, so a clinical mention is not buried under marketing noise.",
        bullets: [
          "Tasks — open work assigned to you",
          "Comments — mentions addressed to you",
          "Notifications — general system notifications",
          "Deal notifications — pipeline movement",
          "Email reports and insurance email — correspondence needing attention",
          "WhatsApp — unread patient conversations",
        ],
      },
      {
        id: "good-practice",
        heading: "Keeping it useful",
        bullets: [
          "Mention people rather than writing to the room; an unaddressed note is nobody's job",
          "Keep clinical documentation in consultations and medical records, not in CRM notes",
          "Clear your mentions daily, in the same way as the missed-calls list",
        ],
      },
    ],
    related: ["patient-record", "workflows", "communication-logs", "roles-and-permissions"],
    keywords: ["comments", "mentions", "tasks", "notifications", "internal", "collaboration", "unread"],
  },

  {
    slug: "communication-logs",
    title: "Communication logs",
    tagline: "Every conversation the clinic had, including AI calls and chat.",
    category: "communication",
    icon: "inbox",
    appPath: ["Menu", "Chat with Aliice", "Chat Logs"],
    audience: ["staff", "admin"],
    summary:
      "The communication log is the searchable history of conversations: web chat, voice and phone calls including those handled by the AI agent, with transcripts, extracted data and whether the conversation was ever linked to a patient.",
    keyCapabilities: [
      "See conversations across chat, voice calls and phone calls",
      "Filter by type, status, source and whether a patient is linked",
      "Read the message-by-message transcript",
      "See what data the conversation captured",
      "Identify anonymous visitors who left no contact details",
      "Find conversations never linked to a patient",
    ],
    sections: [
      {
        id: "filters",
        heading: "Finding a conversation",
        table: {
          columns: ["Filter", "Options"],
          rows: [
            ["Type", "Chat, voice call or phone call"],
            ["Status", "Active, completed or ended"],
            ["Patient link", "Linked to a patient, or not linked"],
            ["Source", "AI call, workflow, manual or system"],
          ],
        },
        callouts: [
          {
            kind: "tip",
            body: "Filter to not linked to a patient. Those are conversations with someone who never became a record — the cheapest leads you own and the ones most often lost.",
          },
        ],
      },
      {
        id: "reading-a-conversation",
        heading: "Reading a conversation",
        features: [
          {
            name: "Transcript",
            description: "The messages in order. Where nothing was recorded, the log says so rather than showing an empty panel.",
          },
          {
            name: "Visitor information",
            description:
              "Contact details the person gave. Anonymous visitors are labelled as such, so you know there is nothing to follow up on.",
          },
          {
            name: "Extracted data",
            description:
              "What the conversation captured — the treatment of interest, availability, contact details — which is what makes an AI conversation actionable.",
          },
        ],
      },
      {
        id: "using-it",
        heading: "What to use it for",
        bullets: [
          "Check what an AI agent actually told a patient before calling them back",
          "Audit the quality of automated conversations and improve the agent's instructions",
          "Recover an enquiry where the visitor left a number but was never contacted",
          "Settle a dispute about what was agreed on the phone",
        ],
        callouts: [
          {
            kind: "important",
            body: "Transcripts and recordings are personal data. Use them for clinical and quality purposes only, and apply the same confidentiality you would to the patient file.",
          },
        ],
      },
    ],
    related: ["ai-agents", "aliice-assistant", "missed-calls", "email"],
    keywords: ["logs", "conversations", "transcript", "chat logs", "calls", "ai call", "history", "audit"],
  },
];
