import Image from "next/image";
import type { GeneratedScreenshot } from "../content/screenshots.generated";

/**
 * Screenshots are generated by the capture pipeline against an isolated Supabase
 * project, so they contain only synthetic patient data.
 */
export default function DocsScreenshot({ shot }: { shot: GeneratedScreenshot }) {
  return (
    <figure className="mt-5">
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50">
        <Image
          src={shot.src}
          alt={shot.alt}
          width={1440}
          height={900}
          sizes="(min-width: 768px) 720px, 100vw"
          className="h-auto w-full"
        />
      </div>
      <figcaption className="mt-2 text-xs leading-relaxed text-slate-400">{shot.alt}</figcaption>
    </figure>
  );
}
