import {
  Activity,
  BarChart3,
  Bot,
  Boxes,
  Building2,
  CalendarDays,
  CalendarClock,
  ChartPie,
  CircleUser,
  ClipboardList,
  CreditCard,
  FileText,
  FolderOpen,
  GraduationCap,
  Heart,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Mail,
  MessageSquare,
  Megaphone,
  Phone,
  PhoneMissed,
  PiggyBank,
  Receipt,
  Rocket,
  Scan,
  Search,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tags,
  Target,
  TrendingUp,
  Users,
  Workflow,
} from "lucide-react";

/**
 * Whitelist of icons usable from content files. Content stores a string key so
 * the content layer stays plain data.
 */
const ICONS = {
  activity: Activity,
  agent: Bot,
  academy: GraduationCap,
  bank: Landmark,
  bookings: CalendarClock,
  calendar: CalendarDays,
  campaign: Megaphone,
  card: CreditCard,
  chart: BarChart3,
  chat: MessageSquare,
  clipboard: ClipboardList,
  dashboard: LayoutDashboard,
  documents: FolderOpen,
  file: FileText,
  heart: Heart,
  image: ImageIcon,
  inbox: Inbox,
  integrations: Boxes,
  key: KeyRound,
  mail: Mail,
  mobile: Smartphone,
  missedCall: PhoneMissed,
  phone: Phone,
  pie: ChartPie,
  piggy: PiggyBank,
  provider: Building2,
  receipt: Receipt,
  rocket: Rocket,
  scan: Scan,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  support: LifeBuoy,
  tags: Tags,
  target: Target,
  trending: TrendingUp,
  user: CircleUser,
  users: Users,
  workflow: Workflow,
} as const;

export type DocIconName = keyof typeof ICONS;

export function DocIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name as DocIconName] ?? FileText;
  return <Icon className={className} aria-hidden="true" />;
}
