// AUTO-GENERATED by scripts/scrape-services.mjs — do not edit by hand.
// Source: https://ads.aesthetics-ge.ch/en/

export type ClinicService = {
  slug: string;
  name: string;
  title: string;
  categories: string[];
  url: string;
  image: string | null;
  images: string[];
  description: string | null;
};

export const CLINIC_SERVICE_CATEGORIES = [
  "Surgery",
  "Injections",
  "Longevity Medicine",
  "Treatments",
] as const;

export const CLINIC_SERVICES: ClinicService[] = [
  {
    "slug": "breast-augmentation",
    "name": "Breast Augmentation",
    "categories": [
      "Surgery"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/breast-augmentation/",
    "image": "/services/breast-augmentation.png",
    "images": [
      "/services/breast-augmentation.png",
      "/services/breast-augmentation-1.png",
      "/services/breast-augmentation-2.png"
    ],
    "title": "Breast Augmentation in Geneva, Montreux and Gstaad",
    "description": "Choose leading Swiss Aesthetic Clinic for your breast augmentation. Book a free consultation with our experts and get 3D simulation and personal treatment plan. Breast augmentation by fat transfer,"
  },
  {
    "slug": "liposuction",
    "name": "Liposuction",
    "categories": [
      "Surgery"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/liposuction/",
    "image": "/services/liposuction.jpg",
    "images": [
      "/services/liposuction.jpg",
      "/services/liposuction-1.png",
      "/services/liposuction-2.png"
    ],
    "title": "Liposuccion in Geneva, Montreux and Gstaad",
    "description": "Choose leading Swiss Aesthetic Clinic for your body contour improvement. Book a free consultation with our experts and get 3D simulation and personal treatment plan. Effective lipo for chin, neck,"
  },
  {
    "slug": "abdominoplasty",
    "name": "Abdominoplasty",
    "categories": [
      "Surgery"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/abdominoplasty/",
    "image": "/services/abdominoplasty.jpg",
    "images": [
      "/services/abdominoplasty.jpg",
      "/services/abdominoplasty-1.png",
      "/services/abdominoplasty-2.png"
    ],
    "title": "Abdominoplasty: Transform Your Silhouette with Expert Cosmetic Surgery",
    "description": "Discover the transformative potential of abdominoplasty at Aesthetics Geneva. Our expert surgeons offer personalized solutions for a toned, contoured abdomen. Learn more about the procedure, benefits,"
  },
  {
    "slug": "blepharoplasty",
    "name": "Blepharoplasty",
    "categories": [
      "Surgery"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/blepharoplasty/",
    "image": "/services/blepharoplasty.jpg",
    "images": [
      "/services/blepharoplasty.jpg",
      "/services/blepharoplasty-1.jpg",
      "/services/blepharoplasty-2.jpg"
    ],
    "title": "Blepharoplasty: Rejuvenate Your Look with Expert Eyelid Surgery |",
    "description": "Explore the art of blepharoplasty at Aesthetics Geneva. Discover how expert eyelid surgery can revitalize your appearance, enhancing both aesthetics and functionality. Learn about the procedure,"
  },
  {
    "slug": "face-lifting",
    "name": "Face Lifting",
    "categories": [
      "Surgery"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/face-lifting/",
    "image": "/services/face-lifting.jpg",
    "images": [
      "/services/face-lifting.jpg",
      "/services/face-lifting-1.png",
      "/services/face-lifting-2.png"
    ],
    "title": "Facelift in Geneva – Face Lift Surgery & Rejuvenation | A",
    "description": "Facelift in Geneva to restore a youthful appearance and tighten facial skin. Surgical and non-surgical face lift options with natural-looking results."
  },
  {
    "slug": "soft-lift",
    "name": "Soft Lift",
    "categories": [
      "Injections"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/soft-lift/",
    "image": "/services/soft-lift.jpg",
    "images": [
      "/services/soft-lift.jpg",
      "/services/soft-lift-1.jpg",
      "/services/soft-lift-2.jpg"
    ],
    "title": "Soft Lift in Geneva – Non-Surgical Facelift with Fillers | A",
    "description": "Soft lift in Geneva using dermal fillers to restore volume and rejuvenate the face. Non-surgical facelift with natural-looking results."
  },
  {
    "slug": "wrinkles-treatment",
    "name": "Wrinkles Treatment",
    "categories": [
      "Injections",
      "Treatments"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/wrinkles-treatment/",
    "image": "/services/wrinkles-treatment.jpg",
    "images": [
      "/services/wrinkles-treatment.jpg",
      "/services/wrinkles-treatment-1.jpg",
      "/services/wrinkles-treatment-2.jpg"
    ],
    "title": "Wrinkle Treatment in Geneva – Anti-Aging Solutions | Aesthetics C",
    "description": "Wrinkle treatment in Geneva with personalised anti-aging solutions to smooth skin and rejuvenate your face. Natural-looking results and expert care."
  },
  {
    "slug": "fillers",
    "name": "Fillers",
    "categories": [
      "Injections"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/fillers/",
    "image": "/services/fillers.jpg",
    "images": [
      "/services/fillers.jpg",
      "/services/fillers-1.jpg",
      "/services/fillers-2.jpg"
    ],
    "title": "Hyaluronic Acid Fillers in Geneva, Montreux and Gstaad | Aesthetics",
    "description": "Choose leading Swiss Aesthetic Clinic for Hyaluronic Acid treatments. Smooth away lines and wrinkles effortlessly for a refreshed, glowing appearance. Learn more about our filler treatments for a"
  },
  {
    "slug": "skin-boosters-injections",
    "name": "Skinboosters",
    "categories": [
      "Injections"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/skin-boosters-injections/",
    "image": "/services/skin-boosters-injections.jpg",
    "images": [
      "/services/skin-boosters-injections.jpg",
      "/services/skin-boosters-injections-1.jpg",
      "/services/skin-boosters-injections-2.jpg"
    ],
    "title": "Skin Boosters in Geneva – Hydration Injections for Glowing Skin | A",
    "description": "Skin Boosters in Geneva – Hydration Injections for Glowing Skin | Aesthetics Clinic"
  },
  {
    "slug": "exosomes",
    "name": "Exosomes",
    "categories": [
      "Longevity Medicine"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/exosomes/",
    "image": "/services/exosomes.jpg",
    "images": [
      "/services/exosomes.jpg",
      "/services/exosomes-1.jpg",
      "/services/exosomes-2.jpg"
    ],
    "title": "Exosome Therapy in Geneva – Skin & Hair Regeneration | A",
    "description": "Exosome therapy in Geneva for skin rejuvenation and hair restoration. Advanced regenerative treatment for natural-looking results and improved skin quality."
  },
  {
    "slug": "iv-drips",
    "name": "IV Drips",
    "categories": [
      "Longevity Medicine"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/iv-drips/",
    "image": "/services/iv-drips.jpg",
    "images": [
      "/services/iv-drips.jpg",
      "/services/iv-drips-1.jpg",
      "/services/iv-drips-2.jpg"
    ],
    "title": "IV Drips in Gstaad | Aesthetics",
    "description": "Discover infusion treatments in Gstaad to revitalise your health and well-being. Provide your body with essential nutrients through tailor-made therapies carried out by qualified professionals. Book"
  },
  {
    "slug": "laser-hair-removal",
    "name": "Laser Hair Removal",
    "categories": [
      "Treatments"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/laser-hair-removal/",
    "image": "/services/laser-hair-removal.png",
    "images": [
      "/services/laser-hair-removal.png",
      "/services/laser-hair-removal-1.jpg",
      "/services/laser-hair-removal-2.png"
    ],
    "title": "Laser Hair Removal in Geneva – Permanent Hair Reduction | Aesthetics C",
    "description": "Laser hair removal in Geneva for long-term hair reduction. Safe and effective treatment for all areas with smooth, lasting results."
  },
  {
    "slug": "co2-laser-treatment",
    "name": "Fractional Laser CO2",
    "categories": [
      "Treatments"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/co2-laser-treatment/",
    "image": "/services/co2-laser-treatment.jpg",
    "images": [
      "/services/co2-laser-treatment.jpg",
      "/services/co2-laser-treatment-1.jpg",
      "/services/co2-laser-treatment-2.jpg"
    ],
    "title": "CO2 Laser Treatment in Geneva – Skin Resurfacing",
    "description": "CO2 laser treatment in Geneva for skin resurfacing, wrinkle reduction and scar improvement. Safe procedure with natural results by expert specialists."
  },
  {
    "slug": "morpheus8",
    "name": "Morpheus8",
    "categories": [
      "Treatments"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/morpheus8/",
    "image": "/services/morpheus8.jpg",
    "images": [
      "/services/morpheus8.jpg",
      "/services/morpheus8-1.jpg",
      "/services/morpheus8-2.jpg"
    ],
    "title": "Morpheus8 in Geneva – RF Microneedling & Skin Tightening | A",
    "description": "Morpheus8 in Geneva combines microneedling and radiofrequency to tighten skin, reduce wrinkles and improve texture. Advanced treatment with natural results."
  },
  {
    "slug": "cryolipolysis-treatment",
    "name": "Cryolipolysis",
    "categories": [
      "Treatments"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/cryolipolysis-treatment/",
    "image": "/services/cryolipolysis-treatment.jpg",
    "images": [
      "/services/cryolipolysis-treatment.jpg",
      "/services/cryolipolysis-treatment-1.jpg",
      "/services/cryolipolysis-treatment-2.jpg"
    ],
    "title": "Cryolipolysis in Geneva – Fat Freezing Treatment",
    "description": "Cryolipolysis in Geneva to reduce stubborn fat without surgery. Effective fat freezing treatment for body contouring with natural-looking results."
  },
  {
    "slug": "ems-culpt",
    "name": "EMSculpt",
    "categories": [
      "Treatments"
    ],
    "url": "https://ads.aesthetics-ge.ch/en/ems-culpt/",
    "image": "/services/ems-culpt.jpg",
    "images": [
      "/services/ems-culpt.jpg",
      "/services/ems-culpt-1.jpg",
      "/services/ems-culpt-2.jpg"
    ],
    "title": "EMS Culpt | Aesthetics",
    "description": "EMSCULPT in Geneva to build muscle and reduce fat without surgery. Advanced body contouring treatment for a stronger, more defined silhouette."
  }
];
